services:
  # ======== PostgreSQL Database ========
  db:
    image: postgres:16-alpine
    container_name: online_shop_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ======== Redis (Broker) ========
  redis:
    image: redis:7-alpine
    container_name: online_shop_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ======== Django Web ========
  web:
    build: .
    container_name: online_shop_web
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - media_data:/app/media
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
      SECRET_KEY: "django-insecure-j2b+)5&^75bdkdsa06fwhx&^#rwnrftyyjam0ot^9%ofd2nfq+"
      ALLOWED_HOSTS: "*"
      DB_ENGINE: "django.db.backends.postgresql"
      DB_NAME: "shop_db"
      DB_USER: "postgres"
      DB_PASSWORD: "12345678"
      DB_HOST: "db"
      DB_PORT: "5432"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://127.0.0.1:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  # ======== Celery Worker ========
  celery:
    build: .
    container_name: online_shop_celery
    restart: unless-stopped
    command: celery -A config worker -l INFO --pool=solo
    environment:
      DEBUG: "True"
      SECRET_KEY: "django-insecure-j2b+)5&^75bdkdsa06fwhx&^#rwnrftyyjam0ot^9%ofd2nfq+"
      DB_NAME: "shop_db"
      DB_USER: "postgres"
      DB_PASSWORD: "12345678"
      DB_HOST: "db"
      DB_PORT: "5432"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data:
  redis_data:
  media_data: